version: "2.3"

services:
  airflow-base:
    build:
      context: ./airflow/base
      labels:
        description: "Base image for Airflow Nodes"
    image: airflow-base:0.1

  airflow-webui:
    build:
      context: ./airflow/webui
      labels:
        description: "Image for Airflow WebUI for bigdata framework"
    image: airflow-webui:0.1
    links:
      - "airflow-base"

  airflow-scheduler:
    build:
      context: ./airflow/scheduler
      labels:
        description: "Image for Airflow Scheduler for bigdata framework"
    image: airflow-scheduler:0.1
    links:
      - "airflow-base"

  airflow-worker:
    build:
      context: ./airflow/worker
      labels:
        description: "Image for Airflow Worker for bigdata framework"
    image: airflow-worker:0.1
    links:
      - "airflow-base"
